from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_dev_command_surface_has_standard_library_bootstrap_for_setup() -> None:
    source = (ROOT / "scripts/dev.py").read_text(encoding="utf-8")
    bootstrap = (ROOT / "scripts/bootstrap_local_environment.py").read_text(encoding="utf-8")
    assert "except ModuleNotFoundError:  # clean-checkout setup bootstrap" in source
    assert "command_catalog_bootstrap_parse_failed" in source
    assert '"scripts/bootstrap_local_environment.py"' in source
    assert '"--require-hashes", "-r", str(LOCK)' in bootstrap
    assert "000-sentinel-edge-checkout.pth" in bootstrap
    assert "sys.path[0:0]" in bootstrap
    assert "verify_checkout_import" in bootstrap
    assert "PYTHONPATH" in bootstrap


def test_development_lock_is_hash_pinned_and_build_tools_are_separately_pinned() -> None:
    bootstrap = (ROOT / "requirements-bootstrap.lock.txt").read_text(encoding="utf-8")
    development = (ROOT / "requirements-dev.lock.txt").read_text(encoding="utf-8")
    assert "setuptools==84.0.0" in bootstrap
    assert "wheel==0.48.0" in bootstrap
    assert bootstrap.count("--hash=sha256:") >= 2
    assert "# This file was autogenerated by uv" in development
    assert development.count("--hash=sha256:") > 20


def test_release_preflight_requires_exact_locked_setup() -> None:
    source = (ROOT / "scripts/submission_preflight.py").read_text(encoding="utf-8")
    assert 'command_env["SENTINEL_SETUP_REQUIRE_LOCKED"] = "1"' in source
    assert "REQUIRED_LOCAL_COMMANDS[0]" in source


def test_build_system_matches_pinned_bootstrap_tools() -> None:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert 'requires = ["setuptools==84.0.0", "wheel==0.48.0"]' in pyproject
