FROM python:3.13-slim
WORKDIR /workspace
COPY . /workspace
RUN python -m pip install --no-cache-dir --editable ".[test]"
RUN python -m pip install --no-cache-dir "onnxruntime>=1.20,<2"
CMD ["python", "--version"]
