from __future__ import annotations

"""Generate a conservative submission rights inventory.

The inventory records only rights assertions that are evidenced inside the repository.
It does not infer a license for an external asset merely because the asset is present.
"""

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "provenance" / "rights-inventory.json"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def member(path: str, *, category: str, rights_basis: str, redistribution: str, evidence: list[str], notes: str) -> dict[str, object]:
    target = ROOT / path
    if not target.is_file():
        raise SystemExit(f"required rights-inventory member missing: {path}")
    return {
        "path": path,
        "category": category,
        "sha256": sha256(target),
        "bytes": target.stat().st_size,
        "rights_basis": rights_basis,
        "redistribution": redistribution,
        "evidence": evidence,
        "notes": notes,
    }


def main() -> int:
    assets = [
        member(
            "LICENSE",
            category="project_license",
            rights_basis="Apache-2.0 project license",
            redistribution="permitted_under_declared_license",
            evidence=["LICENSE"],
            notes="Repository source and project-authored materials are distributed under the project license unless a more specific notice applies.",
        ),
        member(
            "artifacts/release-models/seismic-onnx-development/model.onnx",
            category="generated_development_model",
            rights_basis="repository-generated development fixture",
            redistribution="permitted_as_project_generated_fixture",
            evidence=["scripts/generate_v021_evidence.py", "fixtures/runtime/seismic-onnx-development.package.json"],
            notes="Small synthetic ONNX graph generated by repository code; it is development/benchmark evidence, not a third-party pretrained model.",
        ),
        member(
            "fixtures/models/wildfire-smoke-quality-dataset.jsonl",
            category="synthetic_model_quality_fixture",
            rights_basis="fixture manifest declares Apache-2.0",
            redistribution="permitted_under_declared_fixture_license",
            evidence=["fixtures/models/wildfire-smoke-quality.manifest.json"],
            notes="Deterministic quality fixture; the manifest is the rights assertion used by the release package.",
        ),
        member(
            "fixtures/camera/wildfire-camera-5fps-development.jsonl",
            category="simulated_sensor_fixture",
            rights_basis="repository-authored deterministic simulation fixture",
            redistribution="permitted_as_project_generated_fixture",
            evidence=["docs/release/EMULATED_ARM64_HACKATHON_PROFILE.md"],
            notes="Structured simulated camera observations; contains no raw third-party camera media.",
        ),
        member(
            "fixtures/sensors/imu-100hz-development.jsonl",
            category="simulated_sensor_fixture",
            rights_basis="repository-authored deterministic simulation fixture",
            redistribution="permitted_as_project_generated_fixture",
            evidence=["docs/release/EMULATED_ARM64_HACKATHON_PROFILE.md"],
            notes="Structured simulated IMU observations; contains no third-party waveform recording.",
        ),
        member(
            "fixtures/scenarios/simultaneous-event.json",
            category="simulated_scenario_fixture",
            rights_basis="repository-authored deterministic scenario",
            redistribution="permitted_as_project_generated_fixture",
            evidence=["docs/release/EMULATED_ARM64_HACKATHON_PROFILE.md"],
            notes="Scenario injection manifest for deterministic Judge proof.",
        ),
        member(
            "fixtures/scenarios/benchmark-open-loop.json",
            category="simulated_benchmark_fixture",
            rights_basis="repository-authored deterministic scenario",
            redistribution="permitted_as_project_generated_fixture",
            evidence=["docs/release/EMULATED_ARM64_HACKATHON_PROFILE.md"],
            notes="Open-loop benchmark schedule generated for the project; no external incident media is bundled.",
        ),
        member(
            "fixtures/media/red-square-with-exif.jpg",
            category="parser_test_fixture",
            rights_basis="repository test fixture; no external provenance claim",
            redistribution="reviewed_for_test_only_distribution",
            evidence=["tests"],
            notes="Synthetic/simple parser fixture. It is not used as incident evidence or a public third-party media asset.",
        ),
        member(
            "fixtures/sources/meteoalarm-fixture.observation.json",
            category="source_contract_fixture",
            rights_basis="fixture metadata declares fixture-internal license",
            redistribution="fixture_only_not_live_source_content",
            evidence=["fixtures/sources/meteoalarm-fixture.policy.json", "fixtures/sources/meteoalarm-fixture.observation.json"],
            notes="Contract fixture only; no live-source dependency or redistribution claim is made for MeteoAlarm operational content.",
        ),
    ]
    payload = {
        "schema": "sentinel-edge.rights-inventory.v1",
        "release_profile": "H0-EMULATED-AARCH64-20260813",
        "project_license": "Apache-2.0",
        "policy": {
            "live_external_sources_required": False,
            "raw_private_media_allowed_in_judge_package": False,
            "unverified_external_media_allowed_in_judge_package": False,
            "credentials_allowed_in_judge_package": False,
            "rights_inference_from_file_presence": False,
        },
        "assets": assets,
        "summary": {
            "asset_count": len(assets),
            "external_live_source_assets": 0,
            "third_party_pretrained_models": 0,
            "raw_private_media_assets": 0,
            "status": "reviewed_for_h0_judge_package",
        },
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
