"""Fail-closed source-tree hygiene checks for release inputs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORBIDDEN_DIRS = {".git", ".idea", ".pytest_cache", "__pycache__", "build", "dist"}
# Local working copies may contain ignored developer/runtime state. It is not
# part of a clean export and must not make a source-tree check fail merely
# because a developer has run tests or setup locally.
IGNORED_WORKTREE_DIRS = {".idea", ".pytest_cache", ".uv-cache", ".tmp", ".venv", "build", "dist", "__pycache__"}
FORBIDDEN_SUFFIXES = (".egg-info", ".pyc", ".pyo")
SECRET_NAMES = {".env", ".env.local", "id_rsa", "id_ed25519", "private.key", "private.pem"}
MUTABLE_NAMES = {"sentinel.db", "state.db", "test.sqlite", "cache.sqlite"}


def violations(root: Path = ROOT) -> list[str]:
    found: list[str] = []
    for path in root.rglob("*"):
        rel = path.relative_to(root)
        if ".git" in rel.parts:
            continue
        if any(part in IGNORED_WORKTREE_DIRS for part in rel.parts):
            continue
        if any(part in FORBIDDEN_DIRS for part in rel.parts):
            found.append(str(rel).replace("\\", "/"))
        elif path.is_dir() and path.name.endswith(".egg-info"):
            # Build metadata is generated by editable/package setup and is
            # excluded from source exports just like other ignored state.
            continue
        elif path.is_file() and path.suffix in FORBIDDEN_SUFFIXES:
            found.append(str(rel).replace("\\", "/"))
        elif path.is_file() and (path.name in SECRET_NAMES or path.name in MUTABLE_NAMES):
            found.append(str(rel).replace("\\", "/"))
    package_roots = sorted(
        p.parent for p in (root / "src").rglob("__init__.py") if p.parent.name == "sentinel_edge"
    )
    if len(package_roots) > 1:
        found.append("duplicate_sentinel_edge_package_sources")
    return sorted(set(found))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    result = {"valid": not violations(args.root), "violations": violations(args.root)}
    print(json.dumps(result, indent=2))
    return 1 if result["violations"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
